examples/todo_app/app/main/models.py
from app.extinsions import db


class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(20), nullable=False)
    is_completed = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        return f"List[task: '{self.task}', Completed: '{self.is_completed}']"

examples/todo_app/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from app.main.models import Todo


class TodoForm(FlaskForm):
    task = StringField("Task", validators=[DataRequired()])
    add = SubmitField("Add")

    def validate_task(self, task):
        task = Todo.query.filter_by(task=task.data).first()
        if task and not task.is_completed:
            raise ValidationError("This Task already exist, complete That first ")

examples/todo_app/app/main/__init__.py
from quart import Blueprint

main = Blueprint(
    "main", __name__, template_folder="templates", static_folder="static", static_url_path="/main"
)

from .routes import *

examples/todo_app/app/main/routes.py
from app.extinsions import db
from app.main import main
from quart import render_template, redirect, url_for
from app.main.models import Todo
from app.main.forms import TodoForm


@main.route("/")
async def home():
    form = TodoForm()
    todos = Todo.query.filter_by(is_completed=False).order_by(Todo.id.desc()).all()
    return await render_template("index.html", todos=todos, form=form)


@main.route("/add", methods=["POST"])
async def add():
    form = TodoForm()
    if form.validate_on_submit():
        task = Todo(task=form.task.data)
        db.session.add(task)
        db.session.commit()
    return redirect(url_for("main.home"))


@main.route("/trash/<int:id>")
async def trash(id):
    task = Todo.query.get(int(id))
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for("main.home"))


@main.route("/check/<int:id>")
async def check(id):
    task = Todo.query.get(int(id))
    task.is_completed = True
    db.session.commit()
    return redirect(url_for("main.home"))

examples/todo_app/app/main/templates/index.html
{% extends 'layout.html' %}
{% block style %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('main.static', filename='css/style.css') }}">
<link rel="stylesheet" href="{{ url_for('main.static', filename='css/model.css') }}">
{% endblock %}

{% block body %}
<div class="container">
      <h2 class="heading">Things Todo</h2>
    <button id="btn" class="add-item">Add Task</button>
    <div class="model-section">
      <div class="model">
        <div class="model--header">
        <h2 class="heading">Add Task </h2>

        </div>
        <!-- Close model--header -->
        <div class="model--body">
        <form action="/add" method="post">
          {{ form.hidden_tag() }}
          {{ form.task(class='get-item', autofocus='autofocus') }}
                {% if form.task.errors %}
                    <ul class="errors">{% for error in form.task.errors %}<li>{{ error }}</li>{% endfor %}</ul>
                {% endif %}
          {{ form.add(class='submit') }}
        </form>
        </div>
      </div>
    <!-- Close model -->
   </div>
      {% for todo in todos %}
      <p class="item">{{ todo.task }}{{ todo.id }}</p>
        <a href="{{ url_for('main.trash', id=todo.id) }}"><img  class="icon trash" src="{{ url_for('static', filename='images/trash.svg') }}" alt=""></a>
        <a href="{{ url_for('main.check', id=todo.id) }}"><img class="icon check" src="{{ url_for('static', filename='images/check.svg') }}" alt=""></a>
      {% endfor %}
</div>
{% endblock %}

{% block script %}
{{ super() }}
<script src="{{ url_for('main.static', filename='js/script.js') }}"></script>
{% endblock %}